processes_2 = [
    {"pid": 1, "burst": 20, "priority": 0},
    {"pid": 2, "burst": 15, "priority": 0},
    {"pid": 3, "burst": 11, "priority": 1},
    {"pid": 4, "burst": 9,  "priority": 1},
    {"pid": 5, "burst": 11, "priority": 2},
    {"pid": 6, "burst": 9,  "priority": 3},
    {"pid": 7, "burst": 12, "priority": 2},
    {"pid": 8, "burst": 14, "priority": 4},
    {"pid": 9, "burst": 15, "priority": 3},
    {"pid":10, "burst": 19, "priority": 2},
    {"pid":11, "burst": 25, "priority": 0},
    {"pid":12, "burst": 21, "priority": 1},
    {"pid":13, "burst": 8,  "priority": 2},
    {"pid":14, "burst": 3,  "priority": 5},
    {"pid":15, "burst": 4,  "priority": 5},
    {"pid":16, "burst": 14, "priority": 4},
    {"pid":17, "burst": 12, "priority": 4},
    {"pid":18, "burst": 10, "priority": 2},
    {"pid":19, "burst": 10, "priority": 3},
    {"pid":20, "burst": 9,  "priority": 2}
]

processes = [
    { "pid": 1,  "arrival": 0,  "burst": 10, "priority": 5 },
    { "pid": 2,  "arrival": 1,  "burst": 3,  "priority": 1 },
    { "pid": 3,  "arrival": 2,  "burst": 15, "priority": 0 },
    { "pid": 4,  "arrival": 3,  "burst": 24, "priority": 4 },
    { "pid": 5,  "arrival": 4,  "burst": 6,  "priority": 2 },
    { "pid": 6,  "arrival": 5,  "burst": 7,  "priority": 0 },
    { "pid": 7,  "arrival": 6,  "burst": 25, "priority": 4 },
    { "pid": 8,  "arrival": 7,  "burst": 14, "priority": 1 },
    { "pid": 9,  "arrival": 8,  "burst": 13, "priority": 2 },
    { "pid": 10, "arrival": 9,  "burst": 9,  "priority": 3 },
    { "pid": 11, "arrival": 10, "burst": 7,  "priority": 4 },
    { "pid": 12, "arrival": 11, "burst": 8,  "priority": 3 },
    { "pid": 13, "arrival": 12, "burst": 5,  "priority": 2 },
    { "pid": 14, "arrival": 13, "burst": 4,  "priority": 1 },
    { "pid": 15, "arrival": 14, "burst": 1,  "priority": 0 },
    { "pid": 16, "arrival": 15, "burst": 11, "priority": 4 },
    { "pid": 17, "arrival": 16, "burst": 16, "priority": 5 },
    { "pid": 18, "arrival": 17, "burst": 17, "priority": 5 },
    { "pid": 19, "arrival": 18, "burst": 18, "priority": 4 },
    { "pid": 20, "arrival": 19, "burst": 20, "priority": 3 }
]
